server:
  port: ${RECOMMENDATION_SERVICE_PORT:8083}

spring:
  application:
    name: recommendation-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/game-cellar}

services:
  game-service:
    url: ${GAME_SERVICE_URL:http://localhost:8081}
  library-service:
    url: ${LIBRARY_SERVICE_URL:http://localhost:8082}